### ISSUE TITLE
aur-sync fails with parallel: This job failed.

### ISSUE THREAD

**Issue by Ashymad** [AladW/aurutils#401]
It only seems to happen for some packages. Trying to sync `perl-latexml-git` results in
```
parallel: This job failed:
wget -qi - -O - ''
parallel: Starting no more jobs. Waiting for 0 jobs to finish.
```
aur fetch and aur build work without problems

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/blob/master/lib/aur-rpc#L27

Sounds like `parallel` is trying to pass standard input as arguments to `wget` (which with `-i -` already takes input from stdin). If standard input is empty, it will fail.

**Comment by AladW** [comment]
https://superuser.com/a/915292 :disappointed: 

Options:
* use `--pipe` (slow?)
* remove `-i -`, use `parallel -r`
* remove `parallel` from `aur-rpc`
  * to retrieve large amounts of metadata (in particular for `aur-search`), `aur-rpc` itself can be run with `parallel`

The last option seems the most sensible to me.

**Comment by AladW** [comment]
3. didn't make sense since URI splitting is done inside `aur-rpc`, it did make sense for `aur-fetch-snapshot`. Anyway https://github.com/AladW/aurutils/commit/e6642fe1c93035ac4f7a57ac555355045588f5c9 should fix this issue

**Comment by JJK96** [comment]
I still have this issue with a build of today that includes that commit.

**Comment by AladW** [comment]
The same error as in https://github.com/AladW/aurutils/issues/401#issue-326335990? Sounds unlikely since I removed `parallel` use from `aur-rpc` completely: https://github.com/AladW/aurutils/blob/master/lib/aur-rpc#L59

**Comment by JJK96** [comment]
Apparently I had not installed the new version yet.
