### ISSUE TITLE
`aur build -D /tmp/` not working after #655

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#665]
I've tried building in `/tmp/` with `aur build -L -f -c -D /tmp -d aur -- -T` but got this error from `aur-chroot`
```
==> ERROR: Please specify a working directory.
```
Look like `-D /tmp` is not passed to `aur chroot` here:
https://github.com/AladW/aurutils/blob/89648ed7b72013f207201c48b810149bf19a92ab/lib/aur-build#L210
bashdb trace: `bashdb /usr/lib/aurutils/aur-build -L -f -c -D /tmp -d aur -- -T`
[![asciicast](https://asciinema.org/a/vYpkfa4u7FUkdoewdN9Y9pEda.svg)](https://asciinema.org/a/vYpkfa4u7FUkdoewdN9Y9pEda)

**Comment by maximbaz** [comment]
This was fixed in https://github.com/AladW/aurutils/pull/664, could you please give it another try?

**Comment by bartoszek** [comment]
@maximbaz Yep, it's works now but still not honoring `aur build -D /tmp` flag.
This `aur-build/aur-chroot` section is inconsistent. It creates `chroot` in default `$directory` defined in `aur-chroot`.
https://github.com/AladW/aurutils/blob/89648ed7b72013f207201c48b810149bf19a92ab/lib/aur-build#L203-L211
Then we call `aur chroot` passing `-r /tmp` flag with `makechrootpkg_args`.
https://github.com/AladW/aurutils/blob/89648ed7b72013f207201c48b810149bf19a92ab/lib/aur-build#L272-L275
Which in turns call `makechrootpkg` with `-r $directory` and also `-r /tmp` from `aur-build -D /tmp`.
https://github.com/AladW/aurutils/blob/89648ed7b72013f207201c48b810149bf19a92ab/lib/aur-chroot#L104-L107

**Comment by bartoszek** [comment]
It should looks like this
```diff
diff --git a/lib/aur-build b/lib/aur-build
index eeb0f42..efd3859 100755
--- a/lib/aur-build
+++ b/lib/aur-build
@@ -106,7 +106,7 @@ while true; do
             repo_add_args+=(-s) ;;
         # chroot options
         -D|--directory)
-            shift; makechrootpkg_args+=(-r "$1") ;;
+            shift; chroot_args+=(-D "$1/aurbuild/$(uname -m)") ;;
         --bind)
             shift; makechrootpkg_args+=(-D "$1") ;;
         --bind-rw)
```

**Comment by AladW** [comment]
#666
